# Generated by Django 5.1.2 on 2024-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(default='mm', max_length=50),
            preserve_default=False,
        ),
    ]
