# Generated by Django 5.1.4 on 2024-12-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_streaming',
        ),
        migrations.RemoveField(
            model_name='event',
            name='signaling_room_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='streaming_url',
        ),
    ]
