# Generated by Django 5.1.4 on 2025-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
