# Generated by Django 5.1.2 on 2024-11-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_tickets',
        ),
    ]
