# Generated by Django 5.1.2 on 2024-11-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_available_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_streaming_sessions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_map_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_streaming',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
