# Generated by Django 5.1.4 on 2025-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_streaming_event_stream_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_streaming',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stream_started_at',
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
