# Generated by Django 5.1.4 on 2024-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
