# Generated by Django 5.1.2 on 2024-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_created_streaming_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
