# Generated by Django 5.1.4 on 2025-01-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_streamsessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamSessions',
        ),
    ]
