# Generated by Django 5.1.4 on 2024-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
