# Generated by Django 5.1.4 on 2024-12-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='qr_code',
        ),
    ]
