# Generated by Django 5.1.4 on 2025-01-16 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_streamsessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_viewers',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_quality',
            field=models.CharField(choices=[('low', '480p'), ('medium', '720p'), ('high', '1080p')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='viewer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_streaming', 'creator_status'], name='events_even_is_stre_04e3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['stream_started_at'], name='events_even_stream__56d4f4_idx'),
        ),
    ]
