# Generated by Django 5.1.4 on 2025-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_enable_chat_event_enable_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
