# Generated by Django 5.1.4 on 2024-12-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
