# Generated by Django 5.1.4 on 2025-01-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_available_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meeting_link',
        ),
    ]
