# Generated by Django 5.1.4 on 2025-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('rejected', 'rejected'), ('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='creator_status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('upcoming', 'upcoming'), ('ongoing', 'ongoing'), ('expired', 'expired')], default='pending', max_length=100, null=True),
        ),
    ]
