# Generated by Django 5.1.4 on 2025-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
