# Generated by Django 5.1.4 on 2025-01-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='status',
        ),
    ]
