# Generated by Django 5.1.4 on 2025-01-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_is_read_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('read', 'Read')], default='sent', max_length=10),
        ),
    ]
