# Generated by Django 5.1.2 on 2024-10-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
