# Generated by Django 5.1.4 on 2025-01-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_creatorprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='attendee/profile_pictures/'),
        ),
    ]
