# Generated by Django 5.1.2 on 2024-10-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_attendeeprofile_creatorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='is_setup_complete',
        ),
    ]
