# Generated by Django 5.1.2 on 2024-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_creatorprofile_is_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='is_setup_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
