# Generated by Django 5.1.2 on 2024-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_creatorprofile_is_setup_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
