# Generated by Django 5.1.2 on 2024-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_accountuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='user_type',
            field=models.CharField(choices=[('attendee', 'attendee'), ('creator', 'creator'), ('admin', 'admin')], max_length=10),
        ),
    ]
